import json
import google.generativeai as genai
import os
from dotenv import load_dotenv
import re

load_dotenv()
api_key = os.getenv("GENAI_API_KEY")
genai.configure(api_key=api_key)

generation_config = {
    "temperature": 0.9,
    "top_p": 1,
    "top_k": 32,
    "max_output_tokens": 8192,
}

safety_settings = [
    {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
    {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_MEDIUM_AND_ABOVE"},
    {
        "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE",
    },
    {
        "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
        "threshold": "BLOCK_MEDIUM_AND_ABOVE",
    },
]

model = genai.GenerativeModel(
    model_name="gemini-pro",
    generation_config=generation_config,
    safety_settings=safety_settings,
)

necessary_words = [
    "therapy", "therapist", "therapists",
    "counseling", "counselor", "counselors",
    "psychologist", "psychologists",
    "psychiatrist", "psychiatrists",
    "mental health", "mental illness",
    "mental wellness", "well-being",
    "emotional well-being", "psychological",
    "psychology", "psychotherapy",
    "mindfulness", "self-care",
    "stress management", "stress relief",
    "anxiety", "depression", "stress",
    "trauma", "PTSD", "panic disorder",
    "phobia", "obsessive-compulsive disorder",
    "social anxiety", "generalized anxiety disorder",
    "mood disorder", "bipolar disorder",
    "eating disorder", "addiction",
    "substance abuse", "self-esteem","suicide"
    "suicide prevention", "support group",
    "mental health awareness",
    "psychoanalysis", "psychodynamic therapy",
    "humanistic therapy", "person-centered therapy",
    "gestalt therapy", "behavior therapy",
    "cognitive therapy", "cognitive-behavioral therapy",
    "rational emotive behavior therapy", "family systems therapy",
    "solution-focused therapy", "narrative therapy",
    "existential therapy", "logotherapy",
    "integrative therapy", "eclectic therapy",
    "expressive therapy", "dance therapy",
    "drama therapy", "play therapy",
    "animal-assisted therapy", "equine therapy",
    "horticultural therapy", "adventure therapy",
    "reality therapy", "transpersonal therapy",
    "mind-body therapy", "body-oriented therapy",
    "somatic therapy", "sensorimotor psychotherapy",
    "attachment-based therapy", "emotional freedom techniques",
    "eye movement desensitization and reprocessing",
    "neurofeedback", "artistic expression",
    "self-compassion", "emotional regulation",
    "stress reduction", "relaxation response",
    "mind-body techniques", "holistic healing",
    "health psychology", "positive affirmations",
    "goal-oriented therapy", "self-improvement",
    "inner peace", "emotional balance",
    "stress resilience", "stress tolerance",
    "mental toughness", "cognitive restructuring",
    "problem-solving therapy", "assertiveness skills",
    "boundary management", "self-assertiveness",
    "self-efficacy", "self-empowerment",
    "self-help strategies", "resilience training",
    "emotional support", "empathy",
    "compassionate listening", "peer support",
    "community resources", "crisis intervention",
    "mental health advocacy", "self-care practices",
    "relaxation techniques", "stress management skills",
    "anger control strategies", "communication techniques",
    "conflict resolution skills", "relationship building",
    "family dynamics", "interpersonal skills",
    "communication patterns", "active listening",
    "effective communication", "assertive communication",
    "conflict resolution strategies", "healthy relationships",
    "relationship satisfaction", "family harmony",
    "group dynamics", "supportive environment",
    "encouragement", "motivation", "inspiration",
    "self-motivation", "self-discipline",
    "perseverance", "resilient mindset",
    "emotional agility", "adaptability", "flexibility",
    "open-mindedness", "optimism", "hopefulness",
    "gratitude", "mindfulness meditation",
    "loving-kindness meditation", "compassion meditation",
    "deep breathing exercises", "guided relaxation",
    "progressive muscle relaxation", "visualization techniques",
    "creative visualization", "guided meditation",
    "mantra meditation", "breathwork", "mindful walking",
    "body scan meditation", "awareness meditation",
    "mindful eating", "mindful movement",
    "mindful listening", "mindful speaking",
    "mindful parenting", "mindful communication",
    "mindful leadership", "mindful decision-making",
    "mindful work", "mindful living", "mindful awareness",
    "mindful presence", "mindful engagement",
    "mindful connection", "mindful relationships",
    "mindful community", "mindful society",
    "mindful planet", "mindful future",
    "emotional well-being", "psychological",
    "psychology", "psychotherapy",
    "mindfulness", "self-care",
    "stress management", "stress relief",
    "anxiety", "depression", "stress",
    "trauma", "PTSD", "panic disorder",
    "phobia", "obsessive-compulsive disorder",
    "social anxiety", "generalized anxiety disorder",
    "mood disorder", "bipolar disorder",
    "eating disorder", "addiction",
    "substance abuse", "self-esteem",
    "suicide prevention", "support group",
    "mental health awareness",
    "coping skills", "positive psychology",
    "relaxation techniques", "anger management",
    "assertiveness training", "communication skills",
    "conflict resolution", "grief counseling",
    "relationship counseling", "family therapy",
    "group therapy", "individual therapy",
    "meditation", "yoga", "breathing exercises",
    "journaling", "art therapy", "music therapy",
    "nature therapy", "pet therapy", "laughter therapy",
    "progressive muscle relaxation", "guided imagery",
    "biofeedback", "hypnotherapy", "mind-body connection",
    "holistic health", "alternative medicine",
    "complementary therapy", "mental resilience",
    "emotional intelligence", "stress coping mechanisms",
    "wellness retreat", "work-life balance",
    "boundary setting", "time management",
    "goal setting", "self-reflection",
    "self-awareness", "self-discovery",
    "personal development", "growth mindset",
    "acceptance and commitment therapy",
    "dialectical behavior therapy", "art of living",
    "life coaching", "spiritual healing",
    "acceptance and commitment therapy", "dialectical behavior therapy",
    "behavioral activation", "emotion-focused therapy",
    "motivational interviewing", "psychodynamic psychotherapy",
    "interpersonal psychotherapy", "eye movement integration",
    "solution-focused brief therapy", "psychoeducational interventions",
    "supportive therapy", "group therapy", "individual therapy",
    "couple therapy", "family therapy", "marital therapy",
    "parent-child interaction therapy", "cognitive remediation therapy",
    "mindfulness-based stress reduction", "mindfulness-based cognitive therapy",
    "mindfulness-based relapse prevention", "mindfulness-based interventions",
    "mindfulness-based therapy", "mindfulness-based techniques",
    "mindfulness-based programs", "mindfulness-based practices",
    "mindfulness-based exercises", "mindfulness-based approaches",
    "mindfulness-based interventions", "mindfulness-based strategies",
    "mindfulness-based coping", "mindfulness-based treatments",
    "mindfulness-based modalities", "mindfulness-based exercises",
    "mindfulness-based activities", "mindfulness-based workshops",
    "mindfulness-based groups", "mindfulness-based sessions",
    "mindfulness-based classes", "mindfulness-based courses",
    "mindfulness-based training", "mindfulness-based education",
    "mindfulness-based programs", "mindfulness-based initiatives",
    "mindfulness-based campaigns", "mindfulness-based movements",
    "mindfulness-based advocacy", "mindfulness-based organizations",
    "mindfulness-based communities", "mindfulness-based societies",
    "mindfulness-based networks", "mindfulness-based platforms",
    "mindfulness-based resources", "mindfulness-based research",
    "mindfulness-based literature", "mindfulness-based studies",
    "mindfulness-based findings", "mindfulness-based evidence",
    "mindfulness-based reviews", "mindfulness-based meta-analyses",
    "mindfulness-based assessments", "mindfulness-based evaluations",
    "mindfulness-based measures", "mindfulness-based outcomes",
    "mindfulness-based benefits", "mindfulness-based effects",
    "mindfulness-based impacts", "mindfulness-based results",
    "mindfulness-based implications", "mindfulness-based recommendations",
    "mindfulness-based guidelines", "mindfulness-based standards",
    "mindfulness-based protocols", "mindfulness-based procedures",
    "mindfulness-based approaches", "mindfulness-based practices",
    "mindfulness-based interventions", "mindfulness-based techniques",
    "mindfulness-based strategies", "mindfulness-based tools",
    "mindfulness-based resources", "mindfulness-based services",
    "mindfulness-based programs", "mindfulness-based initiatives",
    "mindfulness-based efforts", "mindfulness-based activities",
    "mindfulness-based events", "mindfulness-based workshops",
    "mindfulness-based groups", "mindfulness-based sessions",
    "mindfulness-based classes", "mindfulness-based courses",
    "mindfulness-based training", "mindfulness-based education",
    "mindfulness-based opportunities", "mindfulness-based experiences",
    "mindfulness-based exercises", "mindfulness-based practices",
    "mindfulness-based techniques", "mindfulness-based strategies",
    "mindfulness-based skills", "mindfulness-based approaches",
    "mindfulness-based habits", "mindfulness-based routines",
    "mindfulness-based rituals", "mindfulness-based traditions",
    "mindfulness-based customs", "mindfulness-based conventions",
    "mindfulness-based norms", "mindfulness-based values",
    "mindfulness-based principles", "mindfulness-based beliefs",
    "mindfulness-based attitudes", "mindfulness-based perspectives",
    "mindfulness-based viewpoints", "mindfulness-based mindsets",
    "mindfulness-based outlooks", "mindfulness-based approaches",
    "mindfulness-based methodologies", "mindfulness-based techniques",
    "mindfulness-based practices", "mindfulness-based strategies",
    "mindfulness-based models", "mindfulness-based frameworks",
    "mindfulness-based theories", "mindfulness-based concepts",
    "mindfulness-based ideas", "mindfulness-based principles",
    "mindfulness-based philosophies", "mindfulness-based paradigms",
    "mindfulness-based perspectives", "mindfulness-based viewpoints",
    "mindfulness-based ideologies", "mindfulness-based approaches",
    "mindfulness-based practices", "mindfulness-based techniques",
    "mindfulness-based strategies", "mindfulness-based solutions",
    "mindfulness-based methods", "mindfulness-based processes",
    "mindfulness-based systems", "mindfulness-based applications",
    "mindfulness-based tools", "mindfulness-based resources",
    "mindfulness-based services", "mindfulness-based programs",
    "mindfulness-based initiatives", "mindfulness-based efforts",
    "mindfulness-based activities", "mindfulness-based events",
    "mindfulness-based workshops", "mindfulness-based groups",
    "mindfulness-based sessions", "mindfulness-based classes",
    "mindfulness-based courses", "mindfulness-based training",
    "mindfulness-based education", "mindfulness-based opportunities",
    "mindfulness-based experiences", "mindfulness-based exercises",
    "mindfulness-based practices", "mindfulness-based techniques",
    "mindfulness-based strategies", "mindfulness-based skills",
    "mindfulness-based approaches", "mindfulness-based habits",
    "mindfulness-based routines", "mindfulness-based rituals",
    "mindfulness-based traditions", "mindfulness-based customs",
    "mindfulness-based conventions", "mindfulness-based norms",
    "mindfulness-based values", "mindfulness-based principles",
    "mindfulness-based beliefs", "mindfulness-based attitudes",
    "mindfulness-based perspectives", "mindfulness-based viewpoints",
    "mindfulness-based mindsets", "mindfulness-based outlooks",
    "mindfulness-based approaches", "mindfulness-based methodologies",
    "mindfulness-based techniques", "mindfulness-based practices",
    "mindfulness-based strategies", "mindfulness-based models",
    "mindfulness-based frameworks", "mindfulness-based theories",
    "mindfulness-based concepts", "mindfulness-based ideas",
    "mindfulness-based principles", "mindfulness-based philosophies",
    "mindfulness-based paradigms", "mindfulness-based perspectives",
    "mindfulness-based viewpoints", "mindfulness-based ideologies",
    "mindfulness-based approaches", "mindfulness-based practices",
    "mindfulness-based techniques", "mindfulness-based strategies",
    "mindfulness-based solutions", "mindfulness-based methods",
    "mindfulness-based processes", "mindfulness-based systems",
    "mindfulness-based applications", "mindfulness-based tools",
    "mindfulness-based resources", "mindfulness-based services",
    "mindfulness-based programs", "mindfulness-based initiatives",
    "mindfulness-based efforts", "mindfulness-based activities",
    "mindfulness-based events", "mindfulness-based workshops",
    "mindfulness-based groups", "mindfulness-based sessions",
    "mindfulness-based classes", "mindfulness-based courses",
    "mindfulness-based training", "mindfulness-based education",
    "mindfulness-based opportunities", "mindfulness-based experiences",
    "mindfulness-based exercises", "mindfulness-based practices",
    "mindfulness-based techniques", "mindfulness-based strategies",
    "mindfulness-based skills", "mindfulness-based approaches",
    "mindfulness-based habits", "mindfulness-based routines",
    "mindfulness-based rituals", "mindfulness-based traditions",
    "mindfulness-based customs", "mindfulness-based conventions",
    "mindfulness-based norms", "mindfulness-based values",
    "mindfulness-based principles", "mindfulness-based beliefs",
    "mindfulness-based attitudes", "mindfulness-based perspectives",
    "mindfulness-based viewpoints", "mindfulness-based mindsets",
    "mindfulness-based outlooks", "mindfulness-based approaches",
    "mindfulness-based methodologies", "mindfulness-based techniques",
    "mindfulness-based practices", "mindfulness-based strategies",
    "mindfulness-based models", "mindfulness-based frameworks",
    "mindfulness-based theories", "mindfulness-based concepts",
    "mindfulness-based ideas", "mindfulness-based principles",
    "mindfulness-based philosophies", "mindfulness-based paradigms",
    "mindfulness-based perspectives", "mindfulness-based viewpoints",
    "mindfulness-based ideologies", "mindfulness-based approaches",
    "mindfulness-based practices", "mindfulness-based techniques",
    "mindfulness-based strategies", "mindfulness-based solutions",
    "mindfulness-based methods", "mindfulness-based processes",
    "mindfulness-based systems", "mindfulness-based applications",
    "mindfulness-based tools", "mindfulness-based resources",
    "mindfulness-based services", "mindfulness-based programs",
    "mindfulness-based initiatives", "mindfulness-based efforts",
    "mindfulness-based activities", "mindfulness-based events",
    "mindfulness-based workshops", "mindfulness-based groups",
    "mindfulness-based sessions", "mindfulness-based classes",
    "mindfulness-based courses", "mindfulness-based training",
    "mindfulness-based education", "mindfulness-based opportunities",
    "mindfulness-based experiences", "mindfulness-based exercises",
    "mindfulness-based practices", "mindfulness-based techniques",
    "mindfulness-based strategies", "mindfulness-based skills",
    "mindfulness-based approaches", "mindfulness-based habits",
    "mindfulness-based routines", "mindfulness-based rituals",
    "mindfulness-based traditions", "mindfulness-based customs",
    "mindfulness-based conventions", "mindfulness-based norms",
    "mindfulness-based values", "mindfulness-based principles",
    "mindfulness-based beliefs", "mindfulness-based attitudes",
    "mindfulness-based perspectives", "mindfulness-based viewpoints",
    "mindfulness-based mindsets", "mindfulness-based outlooks",
    "mindfulness-based approaches", "mindfulness-based methodologies",
    "mindfulness-based techniques", "mindfulness-based practices",
    "mindfulness-based strategies", "mindfulness-based models",
    "mindfulness-based frameworks", "mindfulness-based theories",
    "mindfulness-based concepts", "mindfulness-based ideas",
    "mindfulness-based principles", "mindfulness-based philosophies",
    "mindfulness-based paradigms", "mindfulness-based perspectives",
    "mindfulness-based viewpoints", "mindfulness-based ideologies",
    "mindfulness-based approaches", "mindfulness-based practices",
    "mindfulness-based techniques", "mindfulness-based strategies",
    "mindfulness-based solutions", "mindfulness-based methods",
    "mindfulness-based processes", "mindfulness-based systems",
    "mindfulness-based applications", "mindfulness-based tools",
    "mindfulness-based resources", "mindfulness-based services",
    "mindfulness-based programs", "mindfulness-based initiatives",
    "mindfulness-based efforts", "mindfulness-based activities",
    "mindfulness-based events", "mindfulness-based workshops",
    "mindfulness-based groups", "mindfulness-based sessions",
    "mindfulness-based classes", "mindfulness-based courses",
    "mindfulness-based training", "mindfulness-based education",
    "mindfulness-based opportunities", "mindfulness-based experiences",
    "mindfulness-based exercises", "mindfulness-based practices",
    "mindfulness-based techniques", "mindfulness-based strategies",
    "mindfulness-based skills", "mindfulness-based approaches",
    "mindfulness-based habits", "mindfulness-based routines",
    "mindfulness-based rituals", "mindfulness-based traditions",
    "mindfulness-based customs", "mindfulness-based conventions",
    "mindfulness-based norms", "mindfulness-based values",
    "mindfulness-based principles", "mindfulness-based beliefs",
    "mindfulness-based attitudes", "mindfulness-based perspectives",
    "mindfulness-based viewpoints", "mindfulness-based mindsets",
    "mindfulness-based outlooks", "selfcare",
    "wellness",
    "mindfulness",
    "meditation",
    "relaxation",
    "support",
    "recovery",
    "mindset",
    "selflove",
    "emotionalhealth",
    "positivity",
    "stressrelief",
    "mentalwellbeing",
    "wellbeing",
    "mind",
    "happiness",
    "resilience",
    "coping",
    "balance",
    "selfesteem",
    "selfawareness",
    "growth",
    "calm",
    "breathwork",
    "grounding",
    "reflect",
    "express",
    "acceptance",
    "compassion",
    "community",
    "connection",
    "gratitude",
    "journaling",
    "creativity",
    "exercise",
    "nutrition",
    "sleep",
    "relax",
    "talk",
    "listen",
    "learn",
    "understand",
    "explore",
    "discover",
    "challenge",
    "change",
    "adventure",
    "hope",
    "progress",
    "inspire",
    "motivate",
    "empower",
    "believe",
    "achieve",
    "transform",
    "supportive",
    "positive",
    "healthy",
    "healing",
    "therapeutic",
    "comforting",
    "uplifting",
    "encouraging",
    "reassuring",
    "nurturing",
    "invigorating",
    "refreshing",
    "mindset",
    "selfcare",
    "wellness",
    "breathing",
    "reflection",
    "compassion",
    "meditation",
    "relaxation",
    "support",
    "recovery",
    "mindset",
    "selflove",
    "empathy",
    "positivity",
    "stressrelief",
    "mindfulness",
    "mentalwellbeing",
    "resilience",
    "coping",
    "balance",
    "selfesteem",
    "selfawareness",
    "growth",
    "calm",
    "breathwork",
    "grounding",
    "therapy",
    "expression",
    "acceptance",
    "community",
    "connection",
    "gratitude",
    "journaling",
    "creativity",
    "exercise",
    "nutrition",
    "sleep",
    "relax",
    "talk",
    "listen",
    "learn",
    "understand",
    "explore",
    "discover",
    "challenge",
    "change",
    "adventure",
    "hope",
    "progress",
    "inspire",
    "motivate",
    "empower",
    "believe",
    "achieve",
    "transform",
    "supportive",
    "positive",
    "healthy",
    "healing",
    "therapeutic",
    "comforting",
    "uplifting",
    "encouraging",
    "reassuring",
    "nurturing",
    "invigorating",
    "refreshing"
]
suicide_related_words = [
    "suicide",
    "suicidal",
    "self-harm",
    "suicidal ideation",
    "suicide attempt",
    "suicide prevention",
    "suicide hotline",
    "suicide awareness",
    "suicide risk",
    "suicide survivor",
    "suicide bereavement",
    "suicide intervention",
    "suicide support",
    "suicide prevention program",
    "suicide crisis",
    "suicide helpline",
    "suicide bereavement support",
    "suicide bereavement group",
    "suicide awareness campaign",
    "suicide prevention strategy"
]

# Load conversation history from file
with open("./CSV/conversation_history.json", "r") as file:
    conversation_history = json.load(file)

convo = model.start_chat(history=conversation_history)

def chatbot(user_input):
    convo.send_message(user_input+" Give short answer,do not use my name/username, also answer like you are a friend, make it feel like a human conversation, unless my question is not therapy/mental health related")
    bot_response=convo.last.text
    check=0
    for x in necessary_words:
        if x in bot_response or x in user_input:
            check=1
            bot_response=re.sub(r'[*]', '', bot_response)
            break
    if check==0:
        bot_response="Please ask questions related to therapy or mental wellness"
    else:
        for x in suicide_related_words:
            if x in bot_response or x in user_input:
                bot_response+="\nContact 9152987821 (India) for further assistance on this matter."
                break
    print(bot_response)
    return bot_response